-- Этот файл CLP создан при помощи DB2LOOK Версии "11.5" 
-- Отметка времени: Ср 30 сен 2020 17:15:32
-- Имя базы данных: SAMPLE         
-- Версия менеджера баз данных: DB2/LINUXX8664 Version 11.5.4.0
-- Кодовая страница базы данных: 1208
-- Последовательность слияния базы данных -: IDENTITY
-- Альтернативная последовательность слияния (alt_collate): null
-- Совместимость с varchar2 (varchar2_compat): OFF


-- CONNECT TO SAMPLE;

------------------------------------------------
-- Операторы DDL для схем
------------------------------------------------

-- Запуск приведенного ниже DDL явно создаст в
-- новой базе данных схему, которая соответствует неявно созданной схеме
-- в исходной базе данных.

-- CREATE SCHEMA "NHL27987";


---------------------------------
-- Операторы DDL для последовательностей
---------------------------------


CREATE SEQUENCE "NHL27987"."SAMPSEQUENCE" AS BIGINT
	MINVALUE 1 MAXVALUE 9223372036854775807
	START WITH 1 INCREMENT BY 1
	CACHE 20 NO CYCLE NO ORDER;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."CL_SCHED"
------------------------------------------------
 

CREATE TABLE "NHL27987"."CL_SCHED"  (
		  "CLASS_CODE" CHAR(7 OCTETS) , 
		  "DAY" SMALLINT , 
		  "STARTING" TIME , 
		  "ENDING" TIME )   
		 		 ORGANIZE BY ROW; 






------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."DEPARTMENT"
------------------------------------------------
 

CREATE TABLE "NHL27987"."DEPARTMENT"  (
		  "DEPTNO" CHAR(3 OCTETS) NOT NULL , 
		  "DEPTNAME" VARCHAR(36 OCTETS) NOT NULL , 
		  "MGRNO" CHAR(6 OCTETS) , 
		  "ADMRDEPT" CHAR(3 OCTETS) NOT NULL , 
		  "LOCATION" CHAR(16 OCTETS) )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."DEPARTMENT"

ALTER TABLE "NHL27987"."DEPARTMENT" 
	ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY
		("DEPTNO")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."DEPARTMENT"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."XDEPT2" ON "NHL27987"."DEPARTMENT" 
		("MGRNO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."DEPARTMENT"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."XDEPT3" ON "NHL27987"."DEPARTMENT" 
		("ADMRDEPT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- Операторы DDL для алиасов на основе таблицы "NHL27987"."DEPARTMENT"

CREATE ALIAS "NHL27987"."DEPT" FOR TABLE "NHL27987"."DEPARTMENT";


------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."EMPLOYEE"
------------------------------------------------
 

CREATE TABLE "NHL27987"."EMPLOYEE"  (
		  "EMPNO" CHAR(6 OCTETS) NOT NULL , 
		  "FIRSTNME" VARCHAR(12 OCTETS) NOT NULL , 
		  "MIDINIT" CHAR(1 OCTETS) , 
		  "LASTNAME" VARCHAR(15 OCTETS) NOT NULL , 
		  "WORKDEPT" CHAR(3 OCTETS) , 
		  "PHONENO" CHAR(4 OCTETS) , 
		  "HIREDATE" DATE , 
		  "JOB" CHAR(8 OCTETS) , 
		  "EDLEVEL" SMALLINT NOT NULL , 
		  "SEX" CHAR(1 OCTETS) , 
		  "BIRTHDATE" DATE , 
		  "SALARY" DECIMAL(9,2) , 
		  "BONUS" DECIMAL(9,2) , 
		  "COMM" DECIMAL(9,2) )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."EMPLOYEE"

ALTER TABLE "NHL27987"."EMPLOYEE" 
	ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY
		("EMPNO")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."EMPLOYEE"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."XEMP2" ON "NHL27987"."EMPLOYEE" 
		("WORKDEPT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- Операторы DDL для алиасов на основе таблицы "NHL27987"."EMPLOYEE"

CREATE ALIAS "NHL27987"."EMP" FOR TABLE "NHL27987"."EMPLOYEE";


------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."EMP_PHOTO"
------------------------------------------------
 

CREATE TABLE "NHL27987"."EMP_PHOTO"  (
		  "EMPNO" CHAR(6 OCTETS) NOT NULL , 
		  "PHOTO_FORMAT" VARCHAR(10 OCTETS) NOT NULL , 
		  "PICTURE" BLOB(102400) LOGGED NOT COMPACT )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."EMP_PHOTO"

ALTER TABLE "NHL27987"."EMP_PHOTO" 
	ADD CONSTRAINT "PK_EMP_PHOTO" PRIMARY KEY
		("EMPNO",
		 "PHOTO_FORMAT")
	ENFORCED;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."EMP_RESUME"
------------------------------------------------
 

CREATE TABLE "NHL27987"."EMP_RESUME"  (
		  "EMPNO" CHAR(6 OCTETS) NOT NULL , 
		  "RESUME_FORMAT" VARCHAR(10 OCTETS) NOT NULL , 
		  "RESUME" CLOB(5120 OCTETS) LOGGED NOT COMPACT )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."EMP_RESUME"

ALTER TABLE "NHL27987"."EMP_RESUME" 
	ADD CONSTRAINT "PK_EMP_RESUME" PRIMARY KEY
		("EMPNO",
		 "RESUME_FORMAT")
	ENFORCED;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."PROJECT"
------------------------------------------------
 

CREATE TABLE "NHL27987"."PROJECT"  (
		  "PROJNO" CHAR(6 OCTETS) NOT NULL , 
		  "PROJNAME" VARCHAR(24 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEPTNO" CHAR(3 OCTETS) NOT NULL , 
		  "RESPEMP" CHAR(6 OCTETS) NOT NULL , 
		  "PRSTAFF" DECIMAL(5,2) , 
		  "PRSTDATE" DATE , 
		  "PRENDATE" DATE , 
		  "MAJPROJ" CHAR(6 OCTETS) )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."PROJECT"

ALTER TABLE "NHL27987"."PROJECT" 
	ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY
		("PROJNO")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."PROJECT"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."XPROJ2" ON "NHL27987"."PROJECT" 
		("RESPEMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- Операторы DDL для алиасов на основе таблицы "NHL27987"."PROJECT"

CREATE ALIAS "NHL27987"."PROJ" FOR TABLE "NHL27987"."PROJECT";


------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."PROJACT"
------------------------------------------------
 

CREATE TABLE "NHL27987"."PROJACT"  (
		  "PROJNO" CHAR(6 OCTETS) NOT NULL , 
		  "ACTNO" SMALLINT NOT NULL , 
		  "ACSTAFF" DECIMAL(5,2) , 
		  "ACSTDATE" DATE NOT NULL , 
		  "ACENDATE" DATE )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."PROJACT"

ALTER TABLE "NHL27987"."PROJACT" 
	ADD CONSTRAINT "PK_PROJACT" PRIMARY KEY
		("PROJNO",
		 "ACTNO",
		 "ACSTDATE")
	ENFORCED;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."EMPPROJACT"
------------------------------------------------
 

CREATE TABLE "NHL27987"."EMPPROJACT"  (
		  "EMPNO" CHAR(6 OCTETS) NOT NULL , 
		  "PROJNO" CHAR(6 OCTETS) NOT NULL , 
		  "ACTNO" SMALLINT NOT NULL , 
		  "EMPTIME" DECIMAL(5,2) , 
		  "EMSTDATE" DATE , 
		  "EMENDATE" DATE )   
		 		 ORGANIZE BY ROW; 





-- Операторы DDL для алиасов на основе таблицы "NHL27987"."EMPPROJACT"

CREATE ALIAS "NHL27987"."EMPACT" FOR TABLE "NHL27987"."EMPPROJACT";

CREATE ALIAS "NHL27987"."EMP_ACT" FOR TABLE "NHL27987"."EMPPROJACT";


------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."ACT"
------------------------------------------------
 

CREATE TABLE "NHL27987"."ACT"  (
		  "ACTNO" SMALLINT NOT NULL , 
		  "ACTKWD" CHAR(6 OCTETS) NOT NULL , 
		  "ACTDESC" VARCHAR(20 OCTETS) NOT NULL )   
		 		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."ACT"

ALTER TABLE "NHL27987"."ACT" 
	ADD CONSTRAINT "PK_ACT" PRIMARY KEY
		("ACTNO")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."ACT"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "NHL27987"."XACT2" ON "NHL27987"."ACT" 
		("ACTNO" ASC,
		 "ACTKWD" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."IN_TRAY"
------------------------------------------------
 

CREATE TABLE "NHL27987"."IN_TRAY"  (
		  "RECEIVED" TIMESTAMP , 
		  "SOURCE" CHAR(8 OCTETS) , 
		  "SUBJECT" CHAR(64 OCTETS) , 
		  "NOTE_TEXT" VARCHAR(3000 OCTETS) )   
		 		 ORGANIZE BY ROW; 






------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."ORG"
------------------------------------------------
 

CREATE TABLE "NHL27987"."ORG"  (
		  "DEPTNUMB" SMALLINT NOT NULL , 
		  "DEPTNAME" VARCHAR(14 OCTETS) , 
		  "MANAGER" SMALLINT , 
		  "DIVISION" VARCHAR(10 OCTETS) , 
		  "LOCATION" VARCHAR(13 OCTETS) )   
		 		 ORGANIZE BY ROW; 






------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."STAFF"
------------------------------------------------
 

CREATE TABLE "NHL27987"."STAFF"  (
		  "ID" SMALLINT NOT NULL , 
		  "NAME" VARCHAR(9 OCTETS) , 
		  "DEPT" SMALLINT , 
		  "JOB" CHAR(5 OCTETS) , 
		  "YEARS" SMALLINT , 
		  "SALARY" DECIMAL(7,2) , 
		  "COMM" DECIMAL(7,2) )   
		 		 ORGANIZE BY ROW; 






------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."SALES"
------------------------------------------------
 

CREATE TABLE "NHL27987"."SALES"  (
		  "SALES_DATE" DATE , 
		  "SALES_PERSON" VARCHAR(15 OCTETS) , 
		  "REGION" VARCHAR(15 OCTETS) , 
		  "SALES" INTEGER )   
		 		 ORGANIZE BY ROW; 






------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."STAFFG"
------------------------------------------------
 

CREATE TABLE "NHL27987"."STAFFG"  (
		  "ID" SMALLINT NOT NULL , 
		  "NAME" VARGRAPHIC(9 CODEUNITS16) , 
		  "DEPT" SMALLINT , 
		  "JOB" GRAPHIC(5 CODEUNITS16) , 
		  "YEARS" SMALLINT , 
		  "SALARY" DECIMAL(9,0) , 
		  "COMM" DECIMAL(9,0) )   
		 		 ORGANIZE BY ROW; 







------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."EMPMDC"
------------------------------------------------
 

CREATE TABLE "NHL27987"."EMPMDC"  (
		  "EMPNO" INTEGER , 
		  "DEPT" INTEGER , 
		  "DIV" INTEGER )   
		 ORGANIZE BY ROW USING ( 
		  ( "DEPT" ) , 
		  ( "DIV" ) ) 
		 ; 






------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."PRODUCT"
------------------------------------------------
 

CREATE TABLE "NHL27987"."PRODUCT"  (
		  "PID" VARCHAR(10 OCTETS) NOT NULL , 
		  "NAME" VARCHAR(128 OCTETS) , 
		  "PRICE" DECIMAL(30,2) , 
		  "PROMOPRICE" DECIMAL(30,2) , 
		  "PROMOSTART" DATE , 
		  "PROMOEND" DATE , 
		  "DESCRIPTION" XML )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."PRODUCT"

ALTER TABLE "NHL27987"."PRODUCT" 
	ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY
		("PID")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."PRODUCT"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."PROD_NAME_XMLIDX" ON "NHL27987"."PRODUCT" 
		("DESCRIPTION" ASC)
		GENERATE KEY USING XMLPATTERN '/product/description/name'
		  AS SQL VARCHAR  ( 128 OCTETS ) IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."PRODUCT"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."PROD_DETAIL_XMLIDX" ON "NHL27987"."PRODUCT" 
		("DESCRIPTION" ASC)
		GENERATE KEY USING XMLPATTERN '/product/description/detail'
		  AS SQL VARCHAR  HASHED IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."INVENTORY"
------------------------------------------------
 

CREATE TABLE "NHL27987"."INVENTORY"  (
		  "PID" VARCHAR(10 OCTETS) NOT NULL , 
		  "QUANTITY" INTEGER , 
		  "LOCATION" VARCHAR(128 OCTETS) )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."INVENTORY"

ALTER TABLE "NHL27987"."INVENTORY" 
	ADD CONSTRAINT "PK_INVENTORY" PRIMARY KEY
		("PID")
	ENFORCED;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."CUSTOMER"
------------------------------------------------
 

CREATE TABLE "NHL27987"."CUSTOMER"  (
		  "CID" BIGINT NOT NULL , 
		  "INFO" XML , 
		  "HISTORY" XML )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."CUSTOMER"

ALTER TABLE "NHL27987"."CUSTOMER" 
	ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY
		("CID")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."CUSTOMER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "NHL27987"."CUST_CID_XMLIDX" ON "NHL27987"."CUSTOMER" 
		("INFO" ASC)
		GENERATE KEY USING XMLPATTERN '/customerinfo/@Cid'
		  AS SQL DOUBLE   IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."CUSTOMER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."CUST_NAME_XMLIDX" ON "NHL27987"."CUSTOMER" 
		("INFO" ASC)
		GENERATE KEY USING XMLPATTERN '/customerinfo/name'
		  AS SQL VARCHAR  ( 50 OCTETS ) IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."CUSTOMER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."CUST_PHONES_XMLIDX" ON "NHL27987"."CUSTOMER" 
		("INFO" ASC)
		GENERATE KEY USING XMLPATTERN '/customerinfo/phone'
		  AS SQL VARCHAR  ( 25 OCTETS ) IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."CUSTOMER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."CUST_PHONET_XMLIDX" ON "NHL27987"."CUSTOMER" 
		("INFO" ASC)
		GENERATE KEY USING XMLPATTERN '/customerinfo/phone/@type'
		  AS SQL VARCHAR  ( 25 OCTETS ) IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."PURCHASEORDER"
------------------------------------------------
 

CREATE TABLE "NHL27987"."PURCHASEORDER"  (
		  "POID" BIGINT NOT NULL , 
		  "STATUS" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT 'Unshipped' , 
		  "CUSTID" BIGINT , 
		  "ORDERDATE" DATE , 
		  "PORDER" XML , 
		  "COMMENTS" VARCHAR(1000 OCTETS) )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."PURCHASEORDER"

ALTER TABLE "NHL27987"."PURCHASEORDER" 
	ADD CONSTRAINT "PK_PURCHASEORDER" PRIMARY KEY
		("POID")
	ENFORCED;



-- Операторы DDL для индексов таблицы "NHL27987"."PURCHASEORDER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."PO_PRODS_XMLIDX" ON "NHL27987"."PURCHASEORDER" 
		("PORDER" ASC)
		GENERATE KEY USING XMLPATTERN '/PurchaseOrder/itemlist/item/product/@pid'
		  AS SQL DOUBLE   IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."PURCHASEORDER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."PO_CID_XMLIDX" ON "NHL27987"."PURCHASEORDER" 
		("PORDER" ASC)
		GENERATE KEY USING XMLPATTERN '/PurchaseOrder/@Cid'
		  AS SQL DOUBLE   IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- Операторы DDL для индексов таблицы "NHL27987"."PURCHASEORDER"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "NHL27987"."PO_ZIP_XMLIDX" ON "NHL27987"."PURCHASEORDER" 
		("PORDER" ASC)
		GENERATE KEY USING XMLPATTERN '/PurchaseOrder/customerAdr/addr/pcode-zip'
		  AS SQL VARCHAR  ( 16 OCTETS ) IGNORE INVALID VALUES 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."CATALOG"
------------------------------------------------
 

CREATE TABLE "NHL27987"."CATALOG"  (
		  "NAME" VARCHAR(128 OCTETS) NOT NULL , 
		  "CATLOG" XML )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."CATALOG"

ALTER TABLE "NHL27987"."CATALOG" 
	ADD CONSTRAINT "PK_CATALOG" PRIMARY KEY
		("NAME")
	ENFORCED;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."SUPPLIERS"
------------------------------------------------
 

CREATE TABLE "NHL27987"."SUPPLIERS"  (
		  "SID" VARCHAR(10 OCTETS) NOT NULL , 
		  "ADDR" XML )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."SUPPLIERS"

ALTER TABLE "NHL27987"."SUPPLIERS" 
	ADD CONSTRAINT "PK_PRODUCTSUPPLIER" PRIMARY KEY
		("SID")
	ENFORCED;



------------------------------------------------
-- Операторы DDL для таблицы "NHL27987"."PRODUCTSUPPLIER"
------------------------------------------------
 

CREATE TABLE "NHL27987"."PRODUCTSUPPLIER"  (
		  "PID" VARCHAR(10 OCTETS) NOT NULL , 
		  "SID" VARCHAR(10 OCTETS) NOT NULL )   
		 ORGANIZE BY ROW; 


-- Операторы DDL для первичных ключей таблицы "NHL27987"."PRODUCTSUPPLIER"

ALTER TABLE "NHL27987"."PRODUCTSUPPLIER" 
	ADD CONSTRAINT "PK_PRODUCTSUPPLIER" PRIMARY KEY
		("PID",
		 "SID")
	ENFORCED;

----------------------------

-- Операторы DDL для производных таблиц

----------------------------
SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VDEPT      AS SELECT ALL DEPTNO,   DEPTNAME,   MGRNO,   ADMRDEPT
  FROM DEPT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VHDEPT    AS SELECT ALL DEPTNO ,   DEPTNAME,   MGRNO ,   ADMRDEPT,
  LOCATION   FROM DEPT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VEMP    AS SELECT ALL EMPNO ,   FIRSTNME,   MIDINIT ,   LASTNAME,
  WORKDEPT   FROM EMP;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VPROJ    AS SELECT ALL PROJNO, PROJNAME, DEPTNO, RESPEMP, PRSTAFF,
PRSTDATE, PRENDATE, MAJPROJ FROM PROJ;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VACT AS SELECT ALL ACTNO ,   ACTKWD ,   ACTDESC FROM ACT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VPROJACT    AS SELECT ALL PROJNO,ACTNO, ACSTAFF, ACSTDATE, ACENDATE
FROM PROJACT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VEMPPROJACT AS SELECT ALL EMPNO, PROJNO, ACTNO, EMPTIME, EMSTDATE,
EMENDATE FROM EMPPROJACT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VDEPMG1 (DEPTNO, DEPTNAME, MGRNO, FIRSTNME, MIDINIT,   LASTNAME,
ADMRDEPT) AS SELECT ALL DEPTNO, DEPTNAME, EMPNO, FIRSTNME, MIDINIT,   LASTNAME,
ADMRDEPT FROM DEPT LEFT OUTER  JOIN EMP ON MGRNO = EMPNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VEMPDPT1 (DEPTNO, DEPTNAME, EMPNO, FRSTINIT, MIDINIT,   LASTNAME,
WORKDEPT) AS SELECT ALL DEPTNO, DEPTNAME, EMPNO, SUBSTR(FIRSTNME, 1, 1),
MIDINIT,   LASTNAME, WORKDEPT FROM DEPT  RIGHT OUTER JOIN EMP ON WORKDEPT
= DEPTNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VASTRDE1   (DEPT1NO,DEPT1NAM,EMP1NO,EMP1FN,EMP1MI,EMP1LN,TYPE2,
  DEPT2NO,DEPT2NAM,EMP2NO,EMP2FN,EMP2MI,EMP2LN) AS SELECT ALL   D1.DEPTNO,D1.DEPTNAME,D1.MGRNO,D1.FIRSTNME,D1.MIDINIT,
  D1.LASTNAME, '1',   D2.DEPTNO,D2.DEPTNAME,D2.MGRNO,D2.FIRSTNME,D2.MIDINIT,
  D2.LASTNAME FROM VDEPMG1 D1, VDEPMG1 D2 WHERE D1.DEPTNO = D2.ADMRDEPT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VASTRDE2   (DEPT1NO,DEPT1NAM,EMP1NO,EMP1FN,EMP1MI,EMP1LN,TYPE2,
  DEPT2NO,DEPT2NAM,EMP2NO,EMP2FN,EMP2MI,EMP2LN) AS SELECT ALL   D1.DEPTNO,D1.DEPTNAME,D1.MGRNO,D1.FIRSTNME,D1.MIDINIT,
  D1.LASTNAME,'2',   D1.DEPTNO,D1.DEPTNAME,E2.EMPNO,E2.FIRSTNME,E2.MIDINIT,
  E2.LASTNAME FROM VDEPMG1 D1, EMP E2 WHERE D1.DEPTNO = E2.WORKDEPT;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VPROJRE1   (PROJNO,PROJNAME,PROJDEP,RESPEMP,FIRSTNME,MIDINIT,
  LASTNAME,MAJPROJ) AS SELECT ALL   PROJNO,PROJNAME,DEPTNO,EMPNO,FIRSTNME,MIDINIT,
  LASTNAME,MAJPROJ FROM PROJ, EMP WHERE RESPEMP = EMPNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VPSTRDE1   (PROJ1NO,PROJ1NAME,RESP1NO,RESP1FN,RESP1MI,RESP1LN,
  PROJ2NO,PROJ2NAME,RESP2NO,RESP2FN,RESP2MI,RESP2LN) AS SELECT ALL   P1.PROJNO,P1.PROJNAME,P1.RESPEMP,P1.FIRSTNME,P1.MIDINIT,
  P1.LASTNAME,   P2.PROJNO,P2.PROJNAME,P2.RESPEMP,P2.FIRSTNME,P2.MIDINIT,
  P2.LASTNAME FROM VPROJRE1 P1,   VPROJRE1 P2 WHERE P1.PROJNO = P2.MAJPROJ;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VPSTRDE2   (PROJ1NO,PROJ1NAME,RESP1NO,RESP1FN,RESP1MI,RESP1LN,
  PROJ2NO,PROJ2NAME,RESP2NO,RESP2FN,RESP2MI,RESP2LN) AS SELECT ALL   P1.PROJNO,P1.PROJNAME,P1.RESPEMP,P1.FIRSTNME,P1.MIDINIT,
  P1.LASTNAME,   P1.PROJNO,P1.PROJNAME,P1.RESPEMP,P1.FIRSTNME,P1.MIDINIT,
  P1.LASTNAME FROM VPROJRE1 P1 WHERE NOT EXISTS (SELECT * FROM VPROJRE1
P2 WHERE P1.PROJNO = P2.MAJPROJ);


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VFORPLA   (PROJNO,PROJNAME,RESPEMP,PROJDEP,FRSTINIT,MIDINIT,LASTNAME)
AS SELECT ALL F1.PROJNO,PROJNAME,RESPEMP,PROJDEP, SUBSTR(FIRSTNME, 1, 1),
  MIDINIT, LASTNAME FROM VPROJRE1 F1 LEFT OUTER JOIN EMPPROJACT F2 ON F1.PROJNO
= F2.PROJNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VSTAFAC1(PROJNO, ACTNO, ACTDESC, EMPNO, FIRSTNME, MIDINIT, 
    LASTNAME, EMPTIME,STDATE,ENDATE, TYPE) AS SELECT ALL PA.PROJNO, PA.ACTNO,
AC.ACTDESC,' ', ' ', ' ', ' ',   PA.ACSTAFF, PA.ACSTDATE,   PA.ACENDATE,'1'
FROM PROJACT PA, ACT AC  WHERE PA.ACTNO = AC.ACTNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VSTAFAC2 (PROJNO, ACTNO, ACTDESC, EMPNO, FIRSTNME, MIDINIT,
LASTNAME, EMPTIME,STDATE, ENDATE, TYPE) AS SELECT ALL EP.PROJNO, EP.ACTNO,
AC.ACTDESC, EP.EMPNO,EM.FIRSTNME, EM.MIDINIT, EM.LASTNAME, EP.EMPTIME,
EP.EMSTDATE,   EP.EMENDATE,'2' FROM EMPPROJACT EP, ACT AC, EMP EM WHERE
EP.ACTNO = AC.ACTNO AND EP.EMPNO = EM.EMPNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VPHONE   (LASTNAME,   FIRSTNAME,   MIDDLEINITIAL,   PHONENUMBER,
  EMPLOYEENUMBER,   DEPTNUMBER,   DEPTNAME) AS SELECT ALL LASTNAME,   FIRSTNME,
  MIDINIT ,   VALUE(PHONENO,' '),   EMPNO,   DEPTNO,   DEPTNAME FROM EMP,
DEPT WHERE WORKDEPT = DEPTNO;


SET CURRENT SCHEMA = "NHL27987";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","NHL27987";
CREATE VIEW VEMPLP   (EMPLOYEENUMBER,   PHONENUMBER) AS SELECT ALL EMPNO
,   PHONENO FROM EMP;


-- COMMIT WORK;

-- CONNECT RESET;